### PR TITLE
Organizing examples in their own folder

### PR DESCRIPTION
**Pull request by alexdesiqueira**
Adding a folder, `examples`, and putting examples used on `README` within it.

### CODE REVIEW

**Comment by stefanv** [comment]
@alexdesiqueira I was showed a neat trick recently: you attach an image to an issue, and then you can refer to the URL in the main repo without blowing up its size.

The font size on this example image is very large compared to the content of the image!

**Comment by alexdesiqueira** [comment]
Hey @stefanv,
nothing has changed — the images are resulting from the pipeline. I wonder why the fonts appear large there... :thinking:

**Comment by stefanv** [comment]
Yeah, maybe we need to re-render those then.

**Comment by alexdesiqueira** [comment]
Auto-merging this one based on out-of-GH discussion with @stefanv.

**Comment by alexdesiqueira** [comment]
Auto-merging this one, based on out-of-GH discussion with @stefanv.

**Pull request merged**
